### ISSUE TITLE
Request Permissions error

### ISSUE THREAD

**Issue by hainv23** [edufolly/flutter_bluetooth_serial#129]
Hi @edufolly,
Please help me to check this issue when app request location permission

* Problem summary: Here is stack trace

W/InputMethodManager(14946): Ignoring onBind: cur seq=3647, given seq=3646
W/IInputConnectionWrapper(14946): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(14946): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(14946): getTextBeforeCursor on inactive InputConnection
W/Activity(14946): Can request only one set of permissions at a time
E/MethodChannel#flutter_bluetooth_serial/methods(14946): Failed to handle method call
E/MethodChannel#flutter_bluetooth_serial/methods(14946): java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E/MethodChannel#flutter_bluetooth_serial/methods(14946): 	at io.github.edufolly.flutterbluetoothserial.FlutterBluetoothSerialPlugin.onRequestPermissionsResult(FlutterBluetoothSerialPlugin.java:1007)
E/MethodChannel#flutter_bluetooth_serial/methods(14946): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:712)
E/MethodChannel#flutter_bluetooth_serial/methods(14946): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:412)
E/MethodChannel#flutter_bluetooth_serial/methods(14946): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:627)
E/MethodChannel#flutter_bluetooth_serial/methods(14946): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:640)
E/MethodChannel#flutter_bluetooth_serial/methods(14946): 	at android.app.Activity.requestPermissions(Activity.java:5149)
E/MethodChannel#flutter_bluetooth_serial/methods(14946): 	at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:502)
E/MethodChannel#flutter_bluetooth_serial/methods(14946): 	at io.github.edufolly.flutterbluetoothserial.FlutterBluetoothSerialPlugin.ensurePermissions(FlutterBluetoothSerialPlugin.java:992)
E/MethodChannel#flutter_bluetooth_serial/methods(14946): 	at io.github.edufolly.flutterbluetoothserial.FlutterBluetoothSerialPlugin.onMethodCall(FlutterBluetoothSerialPlugin.java:789)
E/MethodChannel#flutter_bluetooth_serial/methods(14946): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter_bluetooth_serial/methods(14946): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_bluetooth_serial/methods(14946): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter_bluetooth_serial/methods(14946): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_bluetooth_serial/methods(14946): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#flutter_bluetooth_serial/methods(14946): 	at android.os.Looper.loop(Looper.java:182)
E/MethodChannel#flutter_bluetooth_serial/methods(14946): 	at android.app.ActivityThread.main(ActivityThread.java:7594)
E/MethodChannel#flutter_bluetooth_serial/methods(14946): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_bluetooth_serial/methods(14946): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/MethodChannel#flutter_bluetooth_serial/methods(14946): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
V/PhoneWindow(14946): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@b5bef3a, this = DecorView@9e4b7eb[MainActivity]
D/Surface (14946): Surface::disconnect(this=0x7639353000,api=1)
D/Surface (14946): Surface::connect(this=0x7639353000,api=1)
D/mali_winsys(14946): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/Surface (14946): Surface::setBufferCount(this=0x7639353000,bufferCount=4)
E/flutter (14946): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, length=0; index=0, null, java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E/flutter (14946): 	at io.github.edufolly.flutterbluetoothserial.FlutterBluetoothSerialPlugin.onRequestPermissionsResult(FlutterBluetoothSerialPlugin.java:1007)
E/flutter (14946): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:712)
E/flutter (14946): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:412)
E/flutter (14946): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:627)
E/flutter (14946): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:640)
E/flutter (14946): 	at android.app.Activity.requestPermissions(Activity.java:5149)
E/flutter (14946): 	at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:502)
E/flutter (14946): 	at io.github.edufolly.flutterbluetoothserial.FlutterBluetoothSerialPlugin.ensurePermissions(FlutterBluetoothSerialPlugin.java:992)
E/flutter (14946): 	at io.github.edufolly.flutterbluetoothserial.FlutterBluetoothSerialPlugin.onMethodCall(FlutterBluetoothSerialPlugin.java:789)
E/flutter (14946): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (14946): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (14946): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (14946): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (14946): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (14946): 	at android.os.Looper.loop(Looper.java:182)
E/flutter (14946): 	at android.app.ActivityThread.main(ActivityThread.java:7594)
E/flutter (14946): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (14946): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/flutter (14946): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
E/flutter (14946): )
E/flutter (14946): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
E/flutter (14946): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (14946): <asynchronous suspension>
E/flutter (14946): #2      FlutterBluetoothSerial.startDiscovery (package:flutter_bluetooth_serial/FlutterBluetoothSerial.dart:207:5)
E/flutter (14946): <asynchronous suspension>
E/flutter (14946): #3      _DevicePageState._startDiscovery.<anonymous closure> (package:meter_data_blue/screens/device_page/device_page.dart)
E/flutter (14946): <asynchronous suspension>
E/flutter (14946): 
D/FlutterBluePlugin(14946): Starting discovery
W/IInputConnectionWrapper(14946): requestCursorAnchorInfo on inactive InputConnection
D/Surface (14946): Surface::disconnect(this=0x7639355000,api=1)
D/Surface (14946): Surface::disconnect(this=0x7639355000,api=-1)
D/Surface (14946): Surface::disconnect(this=0x7639353000,api=1)
V/PhoneWindow(14946): DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@b5bef3a, this = DecorView@9e4b7eb[MainActivity]
V/PhoneWindow(14946): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@b5bef3a, this = DecorView@9e4b7eb[MainActivity]
D/Surface (14946): Surface::connect(this=0x7639354000,api=1)
D/mali_winsys(14946): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/Surface (14946): Surface::setBufferCount(this=0x7639354000,bufferCount=4)
D/Surface (14946): Surface::connect(this=0x76aefc3000,api=1)
D/mali_winsys(14946): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
W/IInputConnectionWrapper(14946): requestCursorAnchorInfo on inactive InputConnection
W/BpBinder(14946): Slow Binder: BpBinder transact took 241 ms, interface=android.gui.IGraphicBufferProducer, code=2 oneway=false
D/Surface (14946): Surface::disconnect(this=0x76aefc3000,api=1)
D/Surface (14946): Surface::disconnect(this=0x76aefc3000,api=-1)
I/Choreographer(14946): Skipped 30 frames!  The application may be doing too much work on its main thread.
D/Surface (14946): Surface::disconnect(this=0x7639354000,api=1)
V/PhoneWindow(14946): DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@b5bef3a, this = DecorView@9e4b7eb[MainActivity]

* Steps to reproduce:

1. Start discovery device bluetooth and app request location permission

* Environment:
- Device install app: Xioami Redmi K30 Ultra, Android 10
- flutter_bluetooth_serial: ^0.2.2
- Flutter 2.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision adc687823a (3 weeks ago) • 2021-04-16 09:40:20 -0700
Engine • revision b09f014e96
Tools • Dart 2.12.3

**Comment by hainv23** [comment]
I try install app on other device: Samsung Galaxy Note 8, Android 9 => App is working normaly

**Comment by hainv23** [comment]
Android 10 or higher, it must have the ACCESS_FINE_LOCATION permission in order to use several methods within the Wi-Fi, Wi-Fi Aware, or Bluetooth APIs.

https://developer.android.com/about/versions/10/privacy/changes

Adding the ACCESS_FINE_LOCATION permission will help it works for Android 10 or higher
