### ISSUE TITLE
Connection between two andriod devices fail 

### ISSUE THREAD

**Issue by sasikdar** [edufolly/flutter_bluetooth_serial#145]
### Problem summary

I am trying to connect two Andriod devices through but the connection can not be established. 
Error trace:
I/flutter (10074): Cannot connect, exception occured
I/flutter (10074): PlatformException(connect_error, read failed, socket might closed or timeout, read ret: -1, java.io.IOException: read failed, socket might closed or timeout, read ret: -1
I/flutter (10074): 	at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:970)
I/flutter (10074): 	at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:984)
I/flutter (10074): 	at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:536)
I/flutter (10074): 	at io.github.edufolly.flutterbluetoothserial.BluetoothConnection.connect(BluetoothConnection.java:57)
I/flutter (10074): 	at io.github.edufolly.flutterbluetoothserial.BluetoothConnection.connect(BluetoothConnection.java:64)
I/flutter (10074): 	at io.github.edufolly.flutterbluetoothserial.FlutterBluetoothSerialPlugin$FlutterBluetoothSerialMethodCallHandler.lambda$onMethodCall$4$FlutterBluetoothSerialPlugin$FlutterBluetoothSerialMethodCallHandler(FlutterBluetoothSerialPlugin.java:1007)
I/flutter (10074): 	at io.github.edufolly.flutterbluetoothserial.-$$Lambda$FlutterBluetoothSerialPlugin$FlutterBluetoothSerialMethodCallHandler$DZLg1SWj2Aas0tcY7uTlx8xsy4Y.run(Unknown Source:10)

### Steps to reproduce

1. Manually pair the two android devices 
2. Open the app on both devices. 
3. Click connect to paired devices to chat
4. Choose the other phone 
5. the app hangs at trying to connect to device

```
a12s:/ $ getprop | grep ro.build
[ro.build.2ndbrand]: [true]
[ro.build.PDA]: [A127FXXU2AUG9]
[ro.build.changelist]: [22187552]
[ro.build.characteristics]: [phone]
[ro.build.date]: [Sat Jul 31 12:30:11 KST 2021]
[ro.build.date.utc]: [1627702211]
[ro.build.description]: [a12snsxx-user 11 RP1A.200720.012 A127FXXU2AUG9 release-keys]
[ro.build.display.id]: [RP1A.200720.012.A127FXXU2AUG9]
[ro.build.display_build_number]: [true]
[ro.build.fingerprint]: [samsung/a12snnxx/a12s:11/RP1A.200720.012/A127FXXU2AUG9:user/release-keys]
[ro.build.flavor]: [a12snsxx-user]
[ro.build.host]: [21DJ6708]
[ro.build.id]: [RP1A.200720.012]
[ro.build.keys]: [test-keys]
[ro.build.official.release]: [true]
[ro.build.product]: [a12s]
[ro.build.selinux]: [1]
[ro.build.selinux.enforce]: [1]
[ro.build.sw_version]: [A127FXXU2AUG9]
[ro.build.system_root_image]: [false]
[ro.build.tags]: [release-keys]
[ro.build.tf_modelnumber]: [SM-A127F]
[ro.build.type]: [user]
[ro.build.user]: [dpi]
[ro.build.version.all_codenames]: [REL]
[ro.build.version.base_os]: []
[ro.build.version.codename]: [REL]
[ro.build.version.incremental]: [A127FXXU2AUG9]
[ro.build.version.min_supported_target_sdk]: [23]
[ro.build.version.preview_sdk]: [0]
[ro.build.version.preview_sdk_fingerprint]: [REL]
[ro.build.version.release]: [11]
[ro.build.version.release_or_codename]: [11]
[ro.build.version.sdk]: [30]
[ro.build.version.security_index]: [1]
[ro.build.version.security_patch]: [2021-08-01]
[ro.build.version.sem]: [3001]
[ro.build.version.sep]: [120100]

Devices used:
Samsung A12
Huweii Mate 20 Lite

**Comment by dhaval-k-simformsolutions** [comment]
@edufolly I am also facing the same issue. Do we have any update on this?
