### ISSUE TITLE
How catch exception: Uncaught exception thrown by finalizer 

### ISSUE THREAD

**Issue by ValeriiKhmelnytskyi** [edufolly/flutter_bluetooth_serial#156]
Hi! I don't understand, where I can catch exception:

E/System  (28789): Uncaught exception thrown by finalizer
E/System  (28789): java.io.IOException: socket not created
E/System  (28789): 	at android.net.LocalSocketImpl.shutdownInput(LocalSocketImpl.java:374)
E/System  (28789): 	at android.net.LocalSocket.shutdownInput(LocalSocket.java:224)
E/System  (28789): 	at android.bluetooth.BluetoothSocket.close(BluetoothSocket.java:612)
E/System  (28789): 	at android.bluetooth.BluetoothSocket.finalize(BluetoothSocket.java:295)
E/System  (28789): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:292)
E/System  (28789): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:279)
E/System  (28789): 	at java.lang.Daemons$Daemon.run(Daemons.java:140)
E/System  (28789): 	at java.lang.Thread.run(Thread.java:923)

**Comment by ValeriiKhmelnytskyi** [comment]
I get this error mostly when my PI script breaks.
