### ISSUE TITLE
Cannot connect to another android device.

### ISSUE THREAD

**Issue by AlphaRosh** [edufolly/flutter_bluetooth_serial#184]
Hello, i am trying to connect and communicate between two android devices.

I am using a Vivo v20 pro and samsung galaxy tab (SMT515) for testing. Both have the demo serial app installed.

To Reproduce: 
1) Open the app on both phone and tab and turned on Bluetooth and location for both of them. 
2) Making one device as discoverable and searching for the device from the other. (I am able to get the device and also pair it.)
3) Go to "Connect to paired device to chat" with both phone and tab, select the device to chat.

On connecting to the device from vs , i get the following exception on trying to chat with the connected device.

![image](https://user-images.githubusercontent.com/53642147/205440845-d9183cd3-24cd-4c79-8b9b-87c349e72619.png)

 > Exception has occurred.
PlatformException (PlatformException(connect_error, read failed, socket might closed or timeout, read ret: -1, java.io.IOException: read failed, socket might closed or timeout, read ret: -1
	at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:970)
	at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:984)
	at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:536)
	at io.github.edufolly.flutterbluetoothserial.BluetoothConnection.connect(BluetoothConnection.java:57)
	at io.github.edufolly.flutterbluetoothserial.BluetoothConnection.connect(BluetoothConnection.java:64)
	at io.github.edufolly.flutterbluetoothserial.FlutterBluetoothSerialPlugin$FlutterBluetoothSerialMethodCallHandler.lambda$onMethodCall$4$FlutterBluetoothSerialPlugin$FlutterBluetoothSerialMethodCallHandler(FlutterBluetoothSerialPlugin.java:1007)
	at io.github.edufolly.flutterbluetoothserial.-$$Lambda$FlutterBluetoothSerialPlugin$FlutterBluetoothSerialMethodCallHandler$DZLg1SWj2Aas0tcY7uTlx8xsy4Y.run(Unknown Source:10)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
, null))

Thanks

**Comment by vytautas-pranskunas-** [comment]
Same here

**Comment by swordyy7** [comment]
Same here

**Comment by dev9828** [comment]
hey? did you solve the issue? i cant connect two phone with same aplication.

**Comment by SrinivasaMurthy91** [comment]
anyone solve the issue? i am unable to connect two mobiles

**Comment by udit6023** [comment]
BluetoothConnection newConnection =
        await BluetoothConnection.toAddress(device.address);
i have passed a raw device's address in the above code still it is not able to connect to that device
were you able to connect to your desired device?

**Comment by SrinivasaMurthy91** [comment]
I am unable to connect to desired device

**Comment by zamirszn** [comment]
I'm facing this too has anyone been able to figure it out
