### ISSUE TITLE
PlatformException(connect_error, java.io.IOException: gatt status 255, java.io.IOException: java.io.IOException: gatt status 255

### ISSUE THREAD

**Issue by ghost** [edufolly/flutter_bluetooth_serial#218]
PlatformException(connect_error, java.io.IOException: gatt status 255, java.io.IOException: java.io.IOException: gatt status 255
      	at io.github.edufolly.flutterbluetoothserial.le.BluetoothConnectionLE.connect(BluetoothConnectionLE.java:103)
      	at io.github.edufolly.flutterbluetoothserial.FlutterBluetoothSerialPlugin$FlutterBluetoothSerialMethodCallHandler.lambda$onMethodCall$4$io-github-edufolly-flutterbluetoothserial-FlutterBluetoothSerialPlugin$FlutterBluetoothSerialMethodCallHandler(FlutterBluetoothSerialPlugin.java:1018)
      	at io.github.edufolly.flutterbluetoothserial.FlutterBluetoothSerialPlugin$FlutterBluetoothSerialMethodCallHandler$$ExternalSyntheticLambda9.run(Unknown Source:10)
      	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
      	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
      	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
      	at java.lang.Thread.run(Thread.java:1012)
      Caused by: java.io.IOException: gatt status 255
      	at io.github.edufolly.flutterbluetoothserial.le.SerialSocket.onConnectionStateChange(SerialSocket.java:205)
      	at android.bluetooth.BluetoothGatt$1$4.run(BluetoothGatt.java:281)
      	at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:823)
      	at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:47)
      	at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:276)
      	at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:201)
      	at android.os.Binder.execTransactInternal(Binder.java:1187)
      	at android.os.Binder.execTransact(Binder.java:1146)
      , null)

**Comment by BhoneThantCho** [comment]
Is it solved?
I also face same problem.
