### ISSUE TITLE
how to testing the plugin with general BLE function with read/ Write the characteristic

### ISSUE THREAD

**Issue by kawingwu-df** [edufolly/flutter_bluetooth_serial#94]
Hi ,

I would like to testing the plugin with a bonding device , once enter the chat page. my issue is fail to connect the device, folllowing is the log message. can you help to solve my testing ? 

ok result to bonding 
=====================
D/FlutterBluePlugin(10917): mDevices size: 1
I/flutter (13249): Bonding with C4:4F:33:16:FA:07...
I/BluetoothDevice(13249): createBond() for device C4:4F:33:**:**:** called by pid: 13249 tid: 13249
D/FlutterBluePlugin(13249): Discovery finished
D/FlutterBluePlugin(13249): Canceling discovery (stream closed)
I/flutter (13249): Bonding with C4:4F:33:16:FA:07 has success.
D/FlutterBluePlugin(10917): mDevices size: 1
===================================

Fail to connect device to testing the Chat function 
===================================
I/flutter (13249): Connect -> selected C4:4F:33:16:FA:07
D/FlutterBluePlugin(13249): Connecting to C4:4F:33:16:FA:07 (id: 1)
D/BluetoothSocket(13249): BT connect calling pid/uid = 13249/10244
W/BluetoothAdapter(13249): getBluetoothService() called with no BluetoothManagerCallback
D/FlutterBluePlugin(10917): mDevices size: 1
D/FlutterBluePlugin(10917): mDevices size: 1
D/FlutterBluePlugin(10917): mDevices size: 1
D/FlutterBluePlugin(10917): mDevices size: 1
I/flutter (13249): Cannot connect, exception occured
I/flutter (13249): PlatformException(connect_error, read failed, socket might closed or timeout, read ret: -1, java.io.IOException: read failed, socket might closed or timeout, read ret: -1
I/flutter (13249): 	at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:796)
I/flutter (13249): 	at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:810)
I/flutter (13249): 	at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:416)
I/flutter (13249): 	at io.github.edufolly.flutterbluetoothserial.BluetoothConnection.connect(BluetoothConnection.java:58)
I/flutter (13249): 	at io.github.edufolly.flutterbluetoothserial.BluetoothConnection.connect(BluetoothConnection.java:65)
I/flutter (13249): 	at io.github.edufolly.flutterbluetoothserial.FlutterBluetoothSerialPlugin.lambda$onMethodCall$0(FlutterBluetoothSerialPlugin.java:880)
I/flutter (13249): 	at io.github.edufolly.flutterbluetoothserial.-$$Lambda$FlutterBluetoothSerialPlugin$ysyByl051NlOhDx-4TeZKtqb1pA.run(Unknown Source:10)
I/flutter (13249): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
I/flutter (13249): 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
I/flutter (13249): 	at ja
D/FlutterBluePlugin(10917): mDevices size: 1
D/FlutterBluePlugin(10917): mDevices size: 1
===================================

**Comment by PsychoXIVI** [comment]
To what device are you connecting to? Are you sure SDP is enabled and configured on the device you are connecting to?
